name: Checkstyle

on:
  push:
    branches:
      - main
      - mlk/approval_testing_stuff

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Change directory to project directory
        run: cd java

      - name: Build with Maven
        run: cd java && mvn -B clean install

      - name: Checkstyle
        run: cd java && mvn checkstyle:check
